version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/accelerator/question-generator-api
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: Dependency_Scripts/stopApplication.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: Dependency_Scripts/startApplication.sh
      timeout: 600
      runas: ubuntu